### ISSUE TITLE
Ubuntu Trusty packages

### ISSUE THREAD

**Issue by JeremyRand** [kdudka/csbuild-deb#1]
It would be nice to have packages for Ubuntu Trusty (at the moment it looks like only Precise is packaged).

**Comment by kdudka** [comment]
Thanks for the notice!  We should also package up2date versions of those packages.  I will take care of that.

**Comment by kdudka** [comment]
I have uploaded u2date packages for Ubuntu Trusty here:
https://kdudka.fedorapeople.org/csbuild/dists/trusty/contrib/binary-amd64/

Please let me know whether they work as expected.
